import type { Skill } from "../orchestrator/types.js";

/**
 * Production engineering skill catalogue imported from
 * https://github.com/yasdelayu/agent-skills (23 skills, MIT/Apache).
 * Each SKILL.md `description` becomes the injected system-prompt fragment,
 * priced in X402 and attributed to its author on the ledger.
 */
export const ENGINEERING_CATALOG: Skill[] = [
  {
    id: "eng-api-and-interface-design",
    name: "Api And Interface Design",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Guides stable API and interface design. Use when designing APIs, module boundaries, or any public interface. Use when creating REST or GraphQL endpoints, defining type contracts between modules, or establishing boundaries between frontend and backend.",
    preferredEngine: "mock-smart",
    priceX402: 400,
    author: "agent:agent-skills",
    rating: 0.82,
  },
  {
    id: "eng-browser-testing-with-devtools",
    name: "Browser Testing With Devtools",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Tests in real browsers via Chrome DevTools MCP. Use when building or debugging anything that runs in a browser. Use when you need to inspect the DOM, capture console errors, analyze network requests, profile performance, or verify visual output with real runtime data. Requires the chrome-devtools MCP server to be configured.",
    preferredEngine: "mock-smart",
    priceX402: 550,
    author: "agent:agent-skills",
    rating: 0.84,
  },
  {
    id: "eng-ci-cd-and-automation",
    name: "Ci Cd And Automation",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Automates CI/CD pipeline setup. Use when setting up or modifying build and deployment pipelines. Use when you need to automate quality gates, configure test runners in CI, or establish deployment strategies.",
    preferredEngine: "mock-smart",
    priceX402: 700,
    author: "agent:agent-skills",
    rating: 0.86,
  },
  {
    id: "eng-code-review-and-quality",
    name: "Code Review And Quality",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Conducts multi-axis code review. Use before merging any change. Use when reviewing code written by yourself, another agent, or a human. Use when you need to assess code quality across multiple dimensions before it enters the main branch.",
    preferredEngine: "mock-smart",
    priceX402: 850,
    author: "agent:agent-skills",
    rating: 0.88,
  },
  {
    id: "eng-code-simplification",
    name: "Code Simplification",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Simplifies code for clarity. Use when refactoring code for clarity without changing behavior. Use when code works but is harder to read, maintain, or extend than it should be. Use when reviewing code that has accumulated unnecessary complexity.",
    preferredEngine: "mock-smart",
    priceX402: 1000,
    author: "agent:agent-skills",
    rating: 0.9,
  },
  {
    id: "eng-context-engineering",
    name: "Context Engineering",
    category: "logic",
    version: "1.0.0",
    systemPrompt:
      "Optimizes agent context setup. Use when starting a new session, when agent output quality degrades, when switching between tasks, or when you need to configure rules files and context for a project.",
    preferredEngine: "mock-smart",
    priceX402: 1150,
    author: "agent:agent-skills",
    rating: 0.92,
  },
  {
    id: "eng-debugging-and-error-recovery",
    name: "Debugging And Error Recovery",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Guides systematic root-cause debugging. Use when tests fail, builds break, behavior doesn't match expectations, or you encounter any unexpected error. Use when you need a systematic approach to finding and fixing the root cause rather than guessing.",
    preferredEngine: "mock-smart",
    priceX402: 1300,
    author: "agent:agent-skills",
    rating: 0.94,
  },
  {
    id: "eng-deprecation-and-migration",
    name: "Deprecation And Migration",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Manages deprecation and migration. Use when removing old systems, APIs, or features. Use when migrating users from one implementation to another. Use when deciding whether to maintain or sunset existing code.",
    preferredEngine: "mock-smart",
    priceX402: 1450,
    author: "agent:agent-skills",
    rating: 0.82,
  },
  {
    id: "eng-documentation-and-adrs",
    name: "Documentation And Adrs",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Records decisions and documentation. Use when making architectural decisions, changing public APIs, shipping features, or when you need to record context that future engineers and agents will need to understand the codebase.",
    preferredEngine: "mock-smart",
    priceX402: 1600,
    author: "agent:agent-skills",
    rating: 0.84,
  },
  {
    id: "eng-doubt-driven-development",
    name: "Doubt Driven Development",
    category: "logic",
    version: "1.0.0",
    systemPrompt:
      "Subjects every non-trivial decision to a fresh-context adversarial review before it stands. Use when correctness matters more than speed, when working in unfamiliar code, when stakes are high (production, security-sensitive logic, irreversible operations), or any time a confident output would be cheaper to verify now than to debug later.",
    preferredEngine: "mock-smart",
    priceX402: 400,
    author: "agent:agent-skills",
    rating: 0.86,
  },
  {
    id: "eng-frontend-ui-engineering",
    name: "Frontend Ui Engineering",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Builds production-quality, accessible, responsive user-facing UIs. Use when building or modifying interfaces and pages, creating components, implementing layouts, meeting WCAG accessibility requirements, managing state, or when the output needs to look and feel production-quality rather than AI-generated.",
    preferredEngine: "mock-smart",
    priceX402: 550,
    author: "agent:agent-skills",
    rating: 0.88,
  },
  {
    id: "eng-git-workflow-and-versioning",
    name: "Git Workflow And Versioning",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Structures git workflow practices. Use when making any code change. Use when committing, branching, resolving conflicts, or when you need to organize work across multiple parallel streams. Use when cutting a release, choosing a semantic version bump, tagging, or writing a changelog.",
    preferredEngine: "mock-smart",
    priceX402: 700,
    author: "agent:agent-skills",
    rating: 0.9,
  },
  {
    id: "eng-idea-refine",
    name: "Idea Refine",
    category: "logic",
    version: "1.0.0",
    systemPrompt:
      "Refines raw ideas into sharp, actionable concepts through structured divergent and convergent thinking. Use when an idea is still vague, when you need to stress-test assumptions before committing to a plan, or when you want to expand options before converging on one. Triggers on \"ideate\", \"refine this idea\", or \"stress-test my plan\".",
    preferredEngine: "mock-smart",
    priceX402: 850,
    author: "agent:agent-skills",
    rating: 0.92,
  },
  {
    id: "eng-incremental-implementation",
    name: "Incremental Implementation",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Delivers changes incrementally. Use when implementing any feature or change that touches more than one file. Use when you're about to write a large amount of code at once, or when a task feels too big to land in one step.",
    preferredEngine: "mock-smart",
    priceX402: 1000,
    author: "agent:agent-skills",
    rating: 0.94,
  },
  {
    id: "eng-interview-me",
    name: "Interview Me",
    category: "logic",
    version: "1.0.0",
    systemPrompt:
      "Extracts what the user actually wants instead of what they think they should want. Achieves this through one-question-at-a-time interview until ~95% confidence about the underlying intent. Use when an ask is underspecified (\"build me X\" without \"for whom\" or \"why now\"), when the user explicitly invokes (\"interview me\", \"grill me\", \"are we sure?\", \"stress-test my thinking\"), or when you catch yourself silently filling in ambiguous requirements before any plan, spec, or code exists.",
    preferredEngine: "mock-smart",
    priceX402: 1150,
    author: "agent:agent-skills",
    rating: 0.82,
  },
  {
    id: "eng-observability-and-instrumentation",
    name: "Observability And Instrumentation",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Instruments code so production behavior is visible and diagnosable. Use when adding logging, metrics, tracing, or alerting. Use when shipping any feature that runs in production and you need evidence it works. Use when production issues are reported but you can't tell what happened from the available data.",
    preferredEngine: "mock-smart",
    priceX402: 1300,
    author: "agent:agent-skills",
    rating: 0.84,
  },
  {
    id: "eng-performance-optimization",
    name: "Performance Optimization",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Optimizes application performance across frontend, backend, queries, and databases. Use when performance requirements exist, when you suspect performance regressions, when Core Web Vitals or load times need improvement, when N+1 query patterns need fixing, or when profiling reveals bottlenecks.",
    preferredEngine: "mock-smart",
    priceX402: 1450,
    author: "agent:agent-skills",
    rating: 0.86,
  },
  {
    id: "eng-planning-and-task-breakdown",
    name: "Planning And Task Breakdown",
    category: "logic",
    version: "1.0.0",
    systemPrompt:
      "Breaks work into ordered tasks. Use when you have a spec or clear requirements and need to break work into implementable tasks. Use when a task feels too large to start, when you need to estimate scope, or when parallel work is possible.",
    preferredEngine: "mock-smart",
    priceX402: 1600,
    author: "agent:agent-skills",
    rating: 0.88,
  },
  {
    id: "eng-security-and-hardening",
    name: "Security And Hardening",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Hardens code against vulnerabilities. Use when handling user input, authentication, data storage, or external integrations. Use when building any feature that accepts untrusted data, manages user sessions, or interacts with third-party services.",
    preferredEngine: "mock-smart",
    priceX402: 400,
    author: "agent:agent-skills",
    rating: 0.9,
  },
  {
    id: "eng-shipping-and-launch",
    name: "Shipping And Launch",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Prepares production launches. Use when preparing to deploy to production. Use when you need a pre-launch checklist, when setting up monitoring, when planning a staged rollout, or when you need a rollback strategy.",
    preferredEngine: "mock-smart",
    priceX402: 550,
    author: "agent:agent-skills",
    rating: 0.92,
  },
  {
    id: "eng-source-driven-development",
    name: "Source Driven Development",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Grounds every implementation decision in official documentation. Use when you want authoritative, source-cited code free from outdated patterns. Use when building with any framework or library where correctness matters.",
    preferredEngine: "mock-smart",
    priceX402: 700,
    author: "agent:agent-skills",
    rating: 0.94,
  },
  {
    id: "eng-spec-driven-development",
    name: "Spec Driven Development",
    category: "logic",
    version: "1.0.0",
    systemPrompt:
      "Creates specs before coding. Use when starting a new project, feature, or significant change and no specification exists yet. Use when requirements are unclear, ambiguous, or only exist as a vague idea.",
    preferredEngine: "mock-smart",
    priceX402: 850,
    author: "agent:agent-skills",
    rating: 0.82,
  },
  {
    id: "eng-test-driven-development",
    name: "Test Driven Development",
    category: "coding",
    version: "1.0.0",
    systemPrompt:
      "Drives development with tests. Use when implementing any logic, fixing any bug, or changing any behavior. Use when you need to prove that code works, when a bug report arrives, or when you're about to modify existing functionality.",
    preferredEngine: "mock-smart",
    priceX402: 1000,
    author: "agent:agent-skills",
    rating: 0.84,
  },
  {
    id: "eng-using-agent-skills",
    name: "Using Agent Skills",
    category: "logic",
    version: "1.0.0",
    systemPrompt:
      "Discovers and invokes agent skills. Use when starting a session or when you need to discover which skill applies to the current task. This is the meta-skill that governs how all other skills are discovered and invoked.",
    preferredEngine: "mock-smart",
    priceX402: 1150,
    author: "agent:agent-skills",
    rating: 0.86,
  },
];
